spring.application.name=bankapi2
spring.mongodb.uri=mongodb+srv://jcrum1115_db_user:pass123@cluster0.rizsyaa.mongodb.net/bankdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://jcrum1115_db_user:pass123@cluster0.rizsyaa.mongodb.net/bankdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=bankdb
