spring.application.name=bankapi2
spring.mongodb.uri=mongodb+srv://jcrum1115_db_user:pass123@cluster0.rizsyaa.mongodb.net/bankdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://jcrum1115_db_user:pass123@cluster0.rizsyaa.mongodb.net/bankdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=bankdb
jwt.secret=YmFua0FwcDJTZWNyZXRLZXlGb3JKV1RBdXRoZW50aWNhdGlvbjIwMjY=
jwt.expiration=86400000
server.port=${PORT:8080}